# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master
- develop

jobs:

- job: Android
  pool:
    vmImage: 'Default'

  variables:
    buildConfiguration: 'Release'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

  steps:
  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/*droid*.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'

  # - task: DownloadSecureFile@1
  #   name: androidKeyStore
  #   displayName: 'Download Android KeyStore file'
  #   inputs:
  #     secureFile: 'pRopiaAndroidSigningCertificate.keystore'

  # - task: AndroidSigning@3
  #   inputs:
  #     apkFiles: '**/*.apk'
  #     apksign: true
  #     apksignerKeystoreFile: 'pRopiaAndroidSigningCertificate.keystore'
  #     apksignerKeystorePassword: '$(androidKeyStorePassword)'
  #     apksignerKeystoreAlias: 'propiaandroidsigningcertificate'
  #     apksignerKeyPassword: '$(androidKeyPassword)'
  #     apksignerArguments: '--verbose'
  #     zipalign: false

  - task: AndroidSigning@3
    inputs:
      apkFiles: '$(outputDirectory)/*.apk'
      apksignerKeystoreFile: 'pRopiaAndroidSigningCertificate.keystore'
      apksignerKeystorePassword: '$(androidKeyStorePassword)'
      apksignerKeystoreAlias: 'propiaandroidsigningcertificate'
      apksignerKeyPassword: '$(androidKeyPassword)'
      apksignerArguments: '--verbose'
      zipalign: false

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(outputDirectory)'

# Xamarin.Android
  - task: AppCenterDistribute@3
    inputs:
      serverEndpoint: 'App Center'
      appSlug: 'pratik.ropia/CheckCheque-1'
      appFile: '$(outputDirectory)/*.apk'
      symbolsOption: 'Android'
      releaseNotesOption: 'input'
      releaseNotesInput: 'New UI for CheckCheque! Check it out!'
      destinationType: 'groups'
      distributionGroupId: '01140a84-1e64-486d-8d44-144932b6df22'

- job: iOS
  pool:
    vmImage: 'macOS 10.13'
  variables:
    buildConfiguration: 'Release'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

  steps:
  # To manually select a Xamarin SDK version on the Hosted macOS agent, enable this script with the SDK version you want to target
  # https://go.microsoft.com/fwlink/?linkid=871629
  - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_18_1 
    displayName: 'Select Xamarin SDK version'
    enabled: true

  - task: NuGetToolInstaller@0

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/*.sln'

  - task: XamariniOS@2
    inputs:
      projectFile: '**/*iOS.csproj'
      configuration: '$(buildConfiguration)'
      buildForSimulator: true
      packageApp: false